r = int(input("enter radius of circle:"))
area =(3.14*r*r)
circumference = (2*3.14*r)
print("Area of cirle is",round(area,2),"sq cm")
print("circumference of circle is ",round(circumference,2),"cm")
